version: "3.7"

services:
  frontend:
    image: ${SWARMLET_REGISTRY}/react-node-frontend
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: https://api.react-node.${DOMAIN}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.react-node-frontend.loadbalancer.server.port=5000
        - traefik.http.routers.react-node-frontend.rule=Host(`react-node.${DOMAIN}`)
        - traefik.http.routers.react-node-frontend.entrypoints=http,https
        - traefik.http.routers.react-node-frontend.middlewares=redirect@file

  api:
    image: ${SWARMLET_REGISTRY}/react-node-api
    build: ./api
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.react-node-api.loadbalancer.server.port=8080
        - traefik.http.routers.react-node-api.rule=Host(`api.react-node.${DOMAIN}`)
        - traefik.http.routers.react-node-api.entrypoints=http,https
        - traefik.http.routers.react-node-api.middlewares=redirect@file

networks:
  traefik-public:
    external: true
