version: '3.7'

services:
  registry:
    image: registry:2
    restart: always
    # environment:
    #   REGISTRY_AUTH: htpasswd
    #   REGISTRY_AUTH_HTPASSWD_PATH: /basicAuth/security.htpasswd
    #   REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    ports:
      - 5000:5000
    deploy:
      mode: global
    volumes:
      - ./:/basicAuth
    networks:
      - swarmlet-network

networks:
  swarmlet-network:
    external: true
