version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "15000:15000"
      - "15001:15001"
    networks:
      - default
      - traefik-public
      - swarmlet-network
      - gitlab-network
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        from_file('/omnibus_config.rb')
        external_url 'https://gitlab.${DOMAIN}'
        registry_external_url 'https://registry.${DOMAIN}'
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.gitlab.enable=true
        - traefik.gitlab.port=15000
        - traefik.gitlab.frontend.rule=Host:gitlab.${DOMAIN}
        - traefik.gitlab.frontend.entryPoints=http,https
        - traefik.gitlab.frontend.passHostHeader=true
        - traefik.gitlab.frontend.headers.SSLRedirect=true
        - traefik.gitlab.frontend.headers.SSLHost=gitlab.${DOMAIN}
        - traefik.gitlab.frontend.headers.STSIncludeSubdomains=true
        - traefik.gitlab.frontend.headers.STSPreload=true
        - traefik.registry.enable=true
        - traefik.registry.port=15001
        - traefik.registry.frontend.rule=Host:registry.${DOMAIN}
        - traefik.registry.frontend.entryPoints=http,https
        - traefik.registry.frontend.passHostHeader=true
        - traefik.registry.frontend.headers.SSLRedirect=true
        - traefik.registry.frontend.headers.SSLHost=registry.${DOMAIN}
        - traefik.registry.frontend.headers.STSIncludeSubdomains=true
        - traefik.registry.frontend.headers.STSPreload=true
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    networks:
      - gitlab-network
    deploy:
      mode: replicated
      replicas: 1

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    file: ./root_password.txt

networks:
  gitlab-network:
  traefik-public:
    external: true
  swarmlet-network:
    external: true
