version: "3.7"

services:
  web-1:
    image: ${SWARMLET_REGISTRY}/python-redis
    build: .
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.python-redis.loadbalancer.server.port=8000
        - traefik.http.routers.python-redis.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.python-redis.entrypoints=http,https
        - traefik.http.routers.python-redis.middlewares=redirect@file
    networks:
      - swarmlet-network
      - traefik-public

  redis:
    image: redis:alpine
    networks:
      - swarmlet-network

networks:
  swarmlet-network:
    external: true
  traefik-public:
    external: true
