---
- name: Update the /etc/hosts file with node name
  tags: etchostsupdate
  become: yes
  become_user: root
  lineinfile:
    path: '/etc/hosts'
    regexp: ".*\t{{ ansible_hostname }}\t{{ ansible_hostname }}"
    line: "{{ ansible_default_ipv4.address }}\t{{ ansible_hostname }}"
    state: present
  register: etchostsupdate
  with_items: '{{ groups.all }}'

- name: Remove unused apt packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
