version: '3.7'

services:
  deploy:
    image: ${DEPLOYER_IMAGE_TAG}
    build: .
    networks:
      - swarmlet-network
    volumes:
      - git-data:/home/git
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  swarmlet-network:
    external: true

volumes:
  git-data:
    external: true
