version: '3.7'

services:
  deploy:
    build: .
    image: ${SWARMLET_REGISTRY}/env
    secrets:
      - swarmlet-user-secrets
    configs:
      - swarmlet-config
    deploy:
      mode: global
      restart_policy:
        condition: always

secrets:
  swarmlet-user-secrets:
    external: true

configs:
  swarmlet-config:
    external: true
