version: "3.7"

# Built-in environment variables
# SWARMLET_REGISTRY // Defaults to the internal swarm registry at localhost:5000/v2

services:
  frontend:
    image: ${SWARMLET_REGISTRY}/static
    build: .
    # volumes:
    #   - /mnt/gfs/test:/usr/share/nginx/html
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.http.services.static.loadbalancer.server.port=5000
        - traefik.http.routers.static.rule=Host(`static.${DOMAIN}`)
        - traefik.http.routers.static.entrypoints=http,https
        - traefik.http.routers.static.middlewares=redirect@file
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
