version: '3.7'

services:
  swarmlet-registry:
    image: registry:2
    ports:
      - 5000:5000
    deploy:
      mode: global
    networks:
      - swarmlet-network

networks:
  swarmlet-network:
    external: true
