version: '3.7'

services:
  web:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      labels:
        - traefik.enable=true
        - traefik.tags=traefik-public
        - traefik.get-swarmlet.port=80
        - traefik.get-swarmlet.frontend.rule=Host:get.${DOMAIN}
        - traefik.get-swarmlet.frontend.entryPoints=http,https
        - traefik.get-swarmlet.frontend.passHostHeader=true
        - traefik.get-swarmlet.frontend.headers.SSLRedirect=true
        - traefik.get-swarmlet.frontend.headers.SSLHost=${DOMAIN}
        - traefik.get-swarmlet.frontend.headers.STSIncludeSubdomains=true
        - traefik.get-swarmlet.frontend.headers.STSPreload=true
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
