---
collections:
  - name: acl
    src: ansible.posix.acl

  - name: crypto
    src: community.crypto

roles:
  - name: swap
    src: geerlingguy.swap

  - name: disk
    src: aeriscloud.disk
    version: v2.6.0

  - name: oh-my-zsh
    src: gantsign.oh-my-zsh
