- name: Test groups
  hosts: leader
  gather_facts: no
  tasks:
    - debug: msg="{{ groups }}"

    - name: Get info on all nodes
      docker_node_info:
      register: result
      connection: local

    - debug: msg="{{ result.nodes[0].Status.Addr }} {{ result.nodes[0].Status.State }}"
    # - debug: msg="{{ item.Status.Addr }} {{ item.Status.State }}"
    #   loop: "{{ result.nodes }}"
# - name: Test docker_inventory
#   hosts: all
#   connection: local
#   gather_facts: no
#   tasks:
#     - debug: msg="play hosts - {{ play_hosts }}"

# - name: Test docker_inventory
#   hosts: all
#   connection: local
#   gather_facts: no
#   tasks:
#     - debug: msg="play hosts - {{ ansible_all_ipv4_addresses }}"
