---
- hosts: swarm
  connection: local
  gather_facts: yes
  become: yes
  vars:
    create_swap: "{{ lookup('env', 'CREATE_SWAP') }}"
    install_zsh: "{{ lookup('env', 'INSTALL_ZSH') }}"
  roles:
    - common
    - disk
    - system
    - role: swap
      when: 'create_swap is defined'
    - role: oh-my-zsh
      users:
        - username: '{{ remote_user }}'
      when: 'install_zsh is defined'
