---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  roles:
    - common
    - disk
    - docker-install
    - docker-configure

- hosts: swarm
  gather_facts: yes
  become: yes
  roles:
    - common
    - disk
    # - docker-join
    # - docker-configure
