---
- hosts: swarmlet
  connection: local
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install pre-requirements
      apt:
        pkg:
          - acl
          - curl
          - apache2-utils
          - software-properties-common
          - ca-certificates
          - gnupg-agent
          - moreutils
          - wget
          - libpcre3
          - xfsprogs
          - btrfs-progs
